### ISSUE TITLE
Immagine su Docker hub

### ISSUE THREAD

**Issue by f2hex** [italia/spid-testenv-docker#1]
Non sembra esserci l'immagine già disponibile su Docker Hub.

**Comment by alexrj** [comment]
È questa: https://hub.docker.com/r/italia/spid-testenv/
Vedi istruzioni su https://github.com/italia/spid-testenv

Questo repository sarà cancellato, abbiamo messo tutto in italia/spid-testenv (@umbros)

**Comment by f2hex** [comment]
Grazie alexrj!
Si ho visto la versione più recente sull'altro repo.
