### ISSUE TITLE
Perché nel servizio WSO2 l'endpoint di login è uguale a quello di logout?

### ISSUE THREAD

**Issue by ncarandini** [italia/spid-testenv-docker#10]
Entrambi gli endpoint single sign-on e single logout del servizio di Identity Provider di WSO2 sono settati a `https://<server_url>:<port>/samlsso`. E' forse un errore di configurazione che è stato fatto durante la creazione dell'immagine docker del servizio o va bene così?

**Comment by amusarra** [comment]
@ncarandini Gli endpoint di ACS e SLO possono essere anche uguali.

**Comment by ncarandini** [comment]
Grazie, non lo sapevo.
