### ISSUE TITLE
Serie infinita di righe di log che informano che l'utente admin@carbon.super si è loggato

### ISSUE THREAD

**Issue by ncarandini** [italia/spid-testenv-docker#11]
Su Windows 10, avviando Docker-composer da PowerShell (non in background) con `docker-compose up`, una volta completato il caricamento del servizio di backlog e del servizio IdP di WSO2, viene mostrata una serie infinita di righe di log in cui si informa che l'utente admin@carbon.super si è loggato

> spid-testenv-identityserver    | [2017-11-12 16:26:07,763]  INFO
> {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} -  'admin@carbon.super [-1234]' logged in at [2017-11-12 16:26:07,763+0000]

Come mai?

**Comment by damikael** [comment]
Il backoffice effettua chiamate in background al wso2 per verificare che l'idp sia effettivamente online e le api disponibili

**Comment by ncarandini** [comment]
Ah, capito, in pratica un ping per poter visualizzare il messaggio `IdP attivo` o `IdP non attivo`.
Buono a sapersi, e di nessun fastidio visto che una volta verificato che tutto funzioni a dovere, ormai avvio sempre in background, con `docker-compose up -d`.
