### ISSUE TITLE
Dove posso trovare i log delle richieste di autenticazione (SAML2) non andate a buon fine?

### ISSUE THREAD

**Issue by ncarandini** [italia/spid-testenv-docker#12]
Quando una richiesta di autenticazione viene rifiutata dal servizio IdP WSO2, mi viene mostrata una pagina web mi dice che l'autenticazione non ha funzionato e di guardare nei log per saperne di più:

> SAML 2.0 based Single Sign-On
> Not a valid SAML 2.0 Request Message! 
> The message was not recognized by the SAML 2.0 SSO Provider. Please check the logs for more details

Per controllare i log mi sono autenticato nel servizio WSO2 (nel mio caso https://localhost:9443, usando admin come utente e password, come riportato nel readme di questo progetto) e sono andato nel tab Monitor, dove ho trovato le sezioni "Application Logs" e "System Logs", ma non ho trovato il log che contenga la mia richiesta.

Dove devo andare per trovare tali log?

**Comment by amusarra** [comment]
@ncarandini Ti conviene filtrare per ERROR. Gli errori più comuni sono che l'SP non è registrato correttamente, l'AuthnRequest fa riferimento ad un SP non registrato oppure c'è qualche errore nella signature. Comunque l'errore è riportato nella SAML Response.

**Comment by ncarandini** [comment]
@amusarra nel server WSO2 esistono molti log, quindi ok filtrare per ERROR (ottimo suggerimento, grazie) ma vorrei anche sapere, se possibile, in quale log specifico devo guardare.
Per quanto riguarda leggere l'errore dallo status della risposta, purtroppo non mi viene inoltrata alcuna risposta. l'errore avviene prima di mostrare la maschera di login all'utente, in quanto è stata rifiutata la richiesta, quindi la risposta è ridirezionata non al mio hend point ma ad una pagina del servizio IdP stesso, col messaggio di errore di cui sopra:
![image](https://user-images.githubusercontent.com/139274/32784630-aa3cc1a0-c94f-11e7-9374-ebb959f125ce.png).
Quindi l'unica è "ravanare" nel log.

**Comment by ncarandini** [comment]
Comunque mi sono reso conto che questa issue in effetti è Off Topic rispetto a questo progetto, quin di la chiuso qui e la riapro nel progetto [Spid Test Environment - Identity Server](https://github.com/italia/spid-testenv-identityserver)
