### ISSUE TITLE
Utilizzare i servizi di backend e di IdP con https senza problemi.

### ISSUE THREAD

**Issue by ncarandini** [italia/spid-testenv-docker#13]
Una volta avviati i siti con `docker-composer up`, la navigazione verso tali siti con un qualsiasi browser mostra un avvertimento che lo identifica come sito non sicuro e per visualizzarlo si devono effettuare una serie di manovre che alla lunga annoiano parecchio.

~~Sarebbe possibile inserire nelle immagini (sia del backend che del servizio IdP) dei certificati self signed che vengano inclusi nelle root-CA dei rispettivi container in modo che la navigazione in Https non faccia scattare ogni volta tale avvertimento?~~

### UPDATE

Dopo il commento di @alexrj ho studiato meglio la questione. Entrambe le immagini (sia del backend che del servizio IdP) contengono già certificati self-signed (e avrei dovuto capirlo subito, visto che usano senza problemi https) per cui ho cancellato la mia proposta.

Nel frattempo ho trovato la procedura da seguire per importare i certificati relativi al servizio di backend per risolvere il problema almeno per tali servizi, ma poiché i certificati sono SHA1 la cosa funziona con Edge ma non con Chrome, che da un po' di tempo non li riconosce più perché insicuri, come commentato nel loro post [SHA-1 Certificates in Chrome](https://security.googleblog.com/2016/11/sha-1-certificates-in-chrome.html).

La procedura è piuttosto semplice ed è riportata nel mio commento più avanti.

**Comment by ncarandini** [comment]
Parlando con @alexrj mi sono reso conto che è sempre meglio evitare di inserire alcun certificato, anche se self signed, in un progetto. Sto lavorando a un'altra strada, se percorribile aprirò un'altra issue o meglio una pull request.

**Comment by alexrj** [comment]
No beh, io mi riferivo alle implementazioni SP; non avevo capito che tu ti riferissi all'IdP di test. In ogni caso non mi pare che la soluzione che proponevi possa funzionare: per evitare gli avvisi dei browser devi usare un certificato firmato da una CA riconosciuta dal browser. Secondo me questa issue (ma non la soluzione proposta) resta valida e si può tenere aperta

**Comment by ncarandini** [comment]
Scusami @alexrj ma il fatto di non aggiungere un certificato self signed ad una soluzione in git-hub è una best practice, che differenza c'è tra un progetto di test di SP e uno di test di IdP ?
Comunque ho molto ancora da imparare (e ci sto lavorando) sui certificati self signed e il loro uso, quindi mi riprometto di tornmare su questa questione tra qualche giorno, in modo da poterci ragionare con maggior cognizione di causa.

**Comment by amusarra** [comment]
Ciao @ncarandini Utilizzare certificati self-signed per ambienti di test è la normalità, in ambienti di certificazione e produzione di andranno poi a mettere certificati rilasciati da una CA autorevole. 

Per esempio, un gruppo ha sviluppato il plugin SPID per Liferay e il loro ambiente demo utilizza dei certificati self-signed https://spid-demo.hetasan.com/come-configurare-il-plugin-liferay-spid

**Comment by ncarandini** [comment]
ciao @amusara, mi sono spiegato male!
Sono pienamente d'accordo nell'usare i certificati self-signed e ne faccio anch'io uso nel progetto [italia/spid-dotnet-sdk](https://github.com/italia/spid-dotnet-sdk).
La questione è se includere un certificato self signed pronto all'uso nei progetti GitHub in modo che chiunque scarichi il progetto se li trovi già pronti (tutt'al più da installare come trusted nel proprio PC) oppure, cosa che io preferisco, documentare gli step necessari affinche ciascuno si crei il proprio self-signed certificate e lo installi dove di dovere. Questa aspetto spesso crea difficoltà ai meno esperti che vogliono semplicemente scaricare da GitHub e avere tutto funzionante, quindi la mia attenzione è rivolta alla massima semplificazione possibile di questo aspetto, senza aprire possibili scenari anche ipoteticamente non sicuri.

**Comment by ncarandini** [comment]
La procedura da eseguire (in Windows) per rendere attendibile il sito di backoffice è la seguente:
1. Clonare in locale il progetto [spid-testenv-backoffice](https://github.com/italia/spid-testenv).
2. Duplicare e rinominare i file `ca-crt.pem` e `client-crt.pem` che si trovano nella cartella "backoffice/certs" del progetto clonato con il suffisso `.crt` (o `.cer`, che funziona allo stesso modo).
3. cliccare col tasto destro su `ca-crt.crt` ed installare il certificato nella cartella dei certificati radice attendibili:
![image](https://user-images.githubusercontent.com/139274/34071410-412ebe12-e276-11e7-84c1-77ca67e44842.png)
![image](https://user-images.githubusercontent.com/139274/34071425-7b2b6b4c-e276-11e7-911b-1f3c0c2c9136.png)
![image](https://user-images.githubusercontent.com/139274/34071484-344cda16-e277-11e7-8f58-61c9d95efb40.png)
![image](https://user-images.githubusercontent.com/139274/34071500-718a4fb2-e277-11e7-9ea7-0084ddd9e220.png)

4. Allo stesso modo importare il certificato `client-crt.cer`, senza però forzare la destinazione:

![image](https://user-images.githubusercontent.com/139274/34071597-732dd414-e278-11e7-899d-b87a6df922e6.png)

Completata la procedura, se tutto è andato bene, aprendo il browser all'indirizzo `https://localhost:8080` la pagina viene caricata da Edge senza alcun warning, mentre con Chrome il problema persiste, ma per via del fatto che la chiave self signed è di tipo SHA-1 (vedi [SHA-1 Certificates in Chrome](https://security.googleblog.com/2016/11/sha-1-certificates-in-chrome.html)).

**Comment by alexrj** [comment]
This issue was moved to italia/spid-testenv#6
