### ISSUE TITLE
How to preload SPs data in the identity server

### ISSUE THREAD

**Issue by svituz** [italia/spid-testenv-docker#14]
Hello,
I would like to have pre-loaded Service Providers in my image, in order to not repeat the SPs creation every time I delete the container. How can I add them in the image (having the XML saved of course)? I know that committing the container is a solution but I would like to extend the image to load the SPs data

**Comment by ncarandini** [comment]
Hi @svituz,
I'm working on this issue. Meanwhile have you resolved?

**Comment by svituz** [comment]
I've found a solution which is not so elegant but is working for me. After I configured the Service Providers using the backoffice, I took the database and jks file from the container and then I recreated the image including those files.
The needed files are:
/spid-testenvironment/is/identity-server/repository/database/WSO2CARBON_DB.h2.db
/spid-testenvironment/is/identity-server/repository/resources/security/wso2carbon.jks
/spid-testenvironment/is/identity-server/repository/resources/security/client-truststore.jks

I think the correct way is described [here](https://docs.wso2.com/display/IS500/Adding+a+Service+Provider+and+Identity+Provider+Using+Configuration+Files), but I couldn't spend more time on that so I adopted the solution I explained which is working fine for me.

**Comment by ncarandini** [comment]
Hi @svituz,
I was thinking to the same solution about recreating the images, but I do agree that using a configuration file is the right way to go, thanks for the link.

**Comment by alexrj** [comment]
This issue was moved to italia/spid-testenv#7
