### ISSUE TITLE
Richiesta chiarimenti su Docker file VS Docker compose

### ISSUE THREAD

**Issue by ncarandini** [italia/spid-testenv-docker#16]
Guardando il contenuto del progetto rimasto spiazzato dalla presenza dei tre file che stanno nella root, oltre al file docker-compose.yml:
- Dockerfile
- config.js
- spidtestenvstart.sh
Questo perché leggendo nel docker-compose.yml mi sembrava chiaro che la buid delle immagini relative ai due servizi avviene tramite i rispettivi Dockerfile contenuti nelle cartelle:
- backoffice
- identity-server
che fanno riferimento alle immagini prodotte dai rispettivi progetti.
Quindi a cosa servono i tre file nella root del progetto?
Inoltre, guardando nei due progetti, non ho trovato alcun file docker per la produzione delle immagini Docker. Chi le crea e le mantiene aggiornate?

**Comment by umbros** [comment]
Ciao @ncarandini il file Dockerfile in root e altri file che vedi è una versione in un unico file di tutta la configurazione attualmente ancora in sviluppo. Sto pensando di passare a swarm o kubernets. Su docker hub ci sono i due progetti (backend e idserver)  https://hub.docker.com/u/italia/

**Comment by ncarandini** [comment]
ciao @umbros, tre considerazioni:
1. Piuttosto che tenere tutto in divenire, suggerisco di fare una branch dove mettere le cose in via di sviluppo e pulire la master in modo da lasciargli solo ciò che funziona, oppure documentare meglio questa cosa (se vuoi posso farlo io).
2. Aprire una issue in cui spieghi in che modo Docker composer è limitante in modo da poterne discutere, perché a mio avviso usare swarm o Kubernetes per una cosa così semplice (due container) mi sembra un po' strano, ma senza contesto non possa doare un parere informato.
3. C'è una PR aperta da molto tempo e piuttosto corposa, andrebbe verificata e accettata o chiusa.

**Comment by ncarandini** [comment]
Grazie @umbros, capito.

**Comment by ncarandini** [comment]
Ma rimane una domanda: a cosa serve fare qui una versione in un unico file, se abbiamo già i relativi progetti che se ne occupano? Sicuramente con un solo file si può avere un solo container, ma non so se questa può essere una motivazione sufficiente.
Io credo che sarebbe invece utile utilizzare il Dockerfile Composer per dare valore aggiunto, se possibile, alla somma dei due progetti, consentendone una facile customizzazione per l'aggiunta dei proprio certificati self-signed e la registrazione del proprio SP nell'IdP server di test. Creando al contempo una buona documentazione al riguardo.
Io ci sto lavorando, appena ho qualcosa di valido da proporre farò una PR.
