### ISSUE TITLE
Uso di Swarm o Kubernettes al posto di Docker Composer

### ISSUE THREAD

**Issue by ncarandini** [italia/spid-testenv-docker#17]
ciao @umbros,
relativamente al fatto che nel rispondermi alla issue #16 hai ventilato l'ipotesi di usare Swarm o Kubernetes al posto di Docker Composer, ho pensato utile aprire una issue separata per poterci ragionare su.
In che modo Docker composer è limitante per mettere su il sito di test locale?
Perché a mio avviso usare Swarm o Kubernetes per una cosa così semplice (due container) mi sembra un po' strano, ma senza contesto non posso andare più in là di questo.

**Comment by alexrj** [comment]
This issue was moved to italia/spid-testenv#8
