### ISSUE TITLE
Nella configurazione di un Service Provider, specificare anche come generare e importare le chiavi 

### ISSUE THREAD

**Issue by musikele** [italia/spid-testenv-docker#6]
Abbiamo avuto non pochi problemi su come configurare un Service Provider  su questo IDP. 
In particolare siamo impazziti su come generare un certificato che piacesse all'IdP e soprattutto su come generare una `AuthnRequest` che fosse accettata dall'IdP.

Gentilmente: 
- fornire un esempio di comando da lanciare per generare il certificato 
- fornire degli screenshot su come si configurare il service provider 
- fornire un esempio di AuthnRequest configurata a dovere, con tanto di campi Signature riempiti

**Comment by ncarandini** [comment]
Come avete risolto? Quale linguaggio e implementazione avete usato per generare l'Authn request?
Io sto lavorando per consentire l'uso di questo progetto in congiunzione con [spid-dotnet-sdk](https://github.com/italia/spid-dotnet-sdk). Nel Readme c'è un esempio d'uso di creazione di un certificato self-signed di test.

**Comment by alexrj** [comment]
This issue was moved to italia/spid-testenv#4
